import type { ProductQnaList } from "../types";

export const productQnasResponseDummy: ProductQnaList = {
  productId: "p-1001",
  page: 1,
  size: 10,
  totalItems: 23,
  totalPages: 3,

  qnas: [
    {
      qnaId: "q101",
      userName: "user***",
      createdAt: "2025-10-05",
      status: "ANSWERED",
      summary: "북 홀더링 언제 입고되나요?",
      questionBody: "입고 예정일 궁금합니다.",
      answerBody: "해당 상품은 10/05 재입고 완료되었습니다.",
      answeredAt: "2025-10-05",
    },
    {
      qnaId: "q102",
      userName: "reader**",
      createdAt: "2025-10-04",
      status: "WAITING",
      summary: "색상 추가 예정 있나요?",
      questionBody: "블루/그린 색상 계획이 있는지 궁금합니다.",
    },
    {
      qnaId: "q103",
      userName: "kk_dev",
      createdAt: "2025-10-03",
      status: "ANSWERED",
      summary: "구성품에 나사 포함인가요?",
      questionBody: "별도 구매인지 같이 오는지 알고 싶어요.",
      answerBody: "기본 구성에 포함입니다.",
      answeredAt: "2025-10-03",
    },
    {
      qnaId: "q104",
      userName: "mike",
      createdAt: "2025-10-02",
      status: "WAITING",
      summary: "A/S 기간은 얼마나 되나요?",
      questionBody: "보증 기간 안내 부탁드립니다.",
    },
    {
    qnaId: "q105",
    userName: "eun***",
    createdAt: "2025-10-02",
    status: "ANSWERED",
    summary: "재질이 미끄럽나요?",
    questionBody: "책 받침 사용 중 미끄럼이 있는지 궁금합니다.",
    answerBody: "바닥에 미끄럼 방지 패드가 적용되어 안정적입니다.",
    answeredAt: "2025-10-02",
    },
    {
    qnaId: "q106",
    userName: "junho**",
    createdAt: "2025-10-02",
    status: "WAITING",
    summary: "해외 배송 가능한가요?",
    questionBody: "일본으로 배송 가능한지 궁금합니다.",
    },
    {
    qnaId: "q107",
    userName: "nari*",
    createdAt: "2025-10-01",
    status: "ANSWERED",
    summary: "세척 방법 알려주세요",
    questionBody: "먼지나 얼룩이 생기면 어떻게 세척하나요?",
    answerBody: "마른 천으로 닦고 심한 얼룩은 중성세제로 가볍게 세척해주세요.",
    answeredAt: "2025-10-01",
    },
    {
    qnaId: "q108",
    userName: "dev_k",
    createdAt: "2025-09-30",
    status: "WAITING",
    summary: "추가 쿠폰 행사 있나요?",
    questionBody: "이달 내 추가 할인 쿠폰 이벤트 계획이 있는지요.",
    },
    {
    qnaId: "q109",
    userName: "yuri**",
    createdAt: "2025-09-30",
    status: "ANSWERED",
    summary: "최대 하중은 얼마인가요?",
    questionBody: "책 여러 권 올려도 되나요? 최대 하중 궁금합니다.",
    answerBody: "권장 하중은 8kg입니다. 그 이상은 파손 위험이 있습니다.",
    answeredAt: "2025-09-30",
    },
    {
    qnaId: "q110",
    userName: "leo***",
    createdAt: "2025-09-29",
    status: "WAITING",
    summary: "설명서 동봉되나요?",
    questionBody: "조립 설명서와 추가 나사가 포함되는지 알고 싶습니다.",
    }
  ],
};
